spring:
  profiles: common
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 28023

---
spring:
  profiles: local
com.jhkj.weapp.upload.parent: G:\\jhkj\\upload
com.jhkj.weapp.upload.temporary: \\temporary

---
spring:
  profiles: production
com.jhkj.weapp.upload.parent: /usr/share/tomcat/webapps/WxImg
com.jhkj.weapp.upload.temporary: /temporary
